package io.github.mojtaba.microservice.starter.shared.model.exception;

// Generated By caracal Framework, Powered by Dr.Adldoost :D
public enum BusinessExceptionCode {
    GENERAL_ERROR(-1),
    SECURITY_UNHANDLED_EXCEPTION(-2),
    JWT_PARSE_EXCEPTION(-3),
    INVALID_LOGIN_TOKEN(-4),
    ACCESS_DENIED(-5),

    NOT_VALID_DATA(2000),


    //Validation
    BAD_INPUT(3000),
    COULD_NOT_STORED_FILE_RETRY(3001),
    COULD_NOT_CREATE_DIRECTORY(3002),
    FILE_NOT_FOUND_PATH(3003),
    IS_MANDETORY(3004),
    TOKEN_EXPIRED(3005),
    NOTIFICATION_INVALID_OTP_VALUE(3006),

    COMMAND_NOT_SUPPORTED(3008),
    REVERSE_COMMAND_NOT_SUPPORTED(3009),

    INVALID_ATTACHMENT(3007),
    BAD_DEATH_STATUS(3008),
    NOT_VALID_GENDER(3009),
    BAD_DATE_FORMAT(3010),
    ;

    private int value;

    public int getValue() {
        return this.value;

    }

    BusinessExceptionCode(int value) {

        this.value = value;

    }

    public static BusinessExceptionCode findByName(String name) {
        for (BusinessExceptionCode v : values()) {
            if (v.name() == name) {
                return v;
            }
        }
        return null;
    }

}
