package io.github.mojtaba.microservice.starter.shared.model.common;

public enum CommandType {

    LOGIN_STATIC,
    HARIM_OTP,
    IAM_LOGIN,
    CHANGE_PASSWORD,
    WALLET_FIND_PAN_BY_PHONE_NO,



    CUSTOMER_PROFILE_GET_CUSTOMER_DTO,
    //PROFILE
    PROFILE_TEST,
    PROFILE_FETCH_CUSTOMER_PROFILE_BY_ID,

    PROFILE_FETCH_CUSTOMER_PROFILE_BY_USERNAME,
    CHANGE_USERNAME,
    CUSTOMER_DETAILS_INFO,

    PROFILE_GET_PROFILE_LIST,
    PROFILE_GET_PROFILE_PHONE,
    PROFILE_ENABLE_CUSTOMER,
    PROFILE_DISABLE_CUSTOMER,
    PROFILE_GET_CUSTOMER_SESSIONS,
    REGSITER_USER,


    //TEST
    TEST_ROLLBACK_COMMAND,

    //USER MANAGEMENT
    SIGN_UP,
    SIGN_IN,
    SIGN_OUT,


    //NOTIFICATION
    NOTIFICATION_SEND_OTP,
    NOTIFICATION_RESEND_OTP,
    NOTIFICATION_SEND_GENERAL_NOTIFICATION,
    NOTIFICATION_SEND_SCHEDULED_NOTIFICATION,
    NOTIFICATION_IS_OTP_VALID,
    NOTIFICATION_SEND_PENDING_NOTIFICATION,
    NOTIFICATION_GET_TRX_REPORT,
    NOTIFICATION_SEND_WAGE_PAYMENT_NOTIFICATION,



    IAM_ACCEPT_TERMS_AND_CONDITIONS,
    IAM_SIGNUP,
    IAM_SIGNUP_CUSTOMER,
    IAM_UPDATE_CLAIMS,
    IAM_GET_ALL_ROLES,
    IAM_SAVE_ROLE,
    IAM_REMOVE_ROLE,
    IAM_GET_ALL_SUPPORTER,
    IAM_GET_USERS,
    IAM_UPDATE_SUPPORTER,
    IAM_MODIFY_USER,
    IAM_OBSERVE,
    IAM_TRUNCATE,
    IAM_TICKET_BULLETIN,
    IAM_RESPONSE_MESSAGE,
    IAM_HISTORY,
    IAM_DELETE_CREDENTIALS,
    IAM_SEARCH_TITLE,
    IAM_CHANGES_PASSWORD,
    IAM_RESET_PASSWORD,
    FETCH_BASE_USER,
    IAM_CLIENT_LOGIN,
    CIF_TICKET_DELETE,
    ALL_TICKET,

    CUSTOMER_PROFILE_FORGET_PASSWORD_CREATE_SESSION,
    CUSTOMER_PROFILE_FORGET_PASSWORD_GET_SESSION,
    CUSTOMER_PROFILE_FORGET_PASSWORD_NCR_INQUIRY,
    CUSTOMER_PROFILE_FORGET_PASSWORD_ADD_DOC_DATA_TO_SESSION,
    CUSTOMER_PROFILE_FORGET_PASSWORD_FINALIZE_SESSION,
    CUSTOMER_PROFILE_LOCK_SESSION_FOR_TELLER,

    CUSTOMER_PROFILE_FORGET_PASSWORD_CHANGE_PASSWORD_REQUEST,

}
