package io.github.mojtaba.microservice.starter.iam.servicemodel.enums;

public enum Claim {
    ALL,
    BACKOFFICE_USER,
    OBSERVING_METRICS,
    READING_TICKETS,
    ANSWERING_TICKETS,
    CDN_LIST, // لیست محتوا
    CDN_BASEINFO_MANAGEMENT, // مدیریت اطلاعات پایه
    CDN_RELEASE_LIST, // لیست نسخ
    CDN_RELEASE_MANAGEMENT, // مدیریت نسخ
    CDN_TEXTUAL_MANAGEMENT, // مدیریت محتوای متنی
    CDN_BINARY_MANAGEMENT, // مدیریت محتوای باینری
    USER_LIST, // لیست کاربران
    USER_MANAGEMENT_CREATE, // ایجاد کاربر
    USER_MANAGEMENT_UPDATE, // بروزرسانی کاربر
    USER_MANAGEMENT_DELETE, // حذف کاربر
    ROLE_LIST, // لیست نقشها
    ROLE_MANAGEMENT_CREATE, // ایجاد نقش
    ROLE_MANAGEMENT_UPDATE, // بروز رسانی نقش
    ROLE_MANAGEMENT_DELETE, // حذف نقش
    CUSTOMER_MANAGEMENT, // مدیریت مشتریان
    CUSTOMER_LOG_LIST, // مشاهده عملکرد مشتریان
    DASHBOARD_OBSERVE, // مشاهده داشبورد
    CRITIC_LIST,// لیست انتقادات و پیشنهادات
    CRITIC_MANAGEMENT, // مدیریت انتقادات و پیشنهادات
    CDN_EKYC_DOCUMENT_UPLOAD, // آپلود فایل در فرایند افتتاح حساب مشتری
    AI_CDN_MANAGEMENT, // مدیریت فایل ها هوش مصنوعی
    AI_SESSION_MANAGEMENT, // مدیریت نشست هوش مصتوعی
    TELLER_CDN_MANAGEMENT, // تلر بانک مدیریت محتوا
    TELLER_SESSION_MANAGEMENT, // تلر بانک مدیریت نشست احراز هویت مشتری
    CARD_ISSUANCE_MANAGEMENT, // مدیریت کارت های افتتاح حساب
    EKYC_SESSION_VIEWER,
    EKYC_DASHBOARD_VIEWER,
    EKYC_VIRTUAL_BRANCH_MANAGER,
    EKYC_COMPLETED_PROCESS_DASHBOARD_VIEWER,
    EKYC_ACTIVATED_CARD_DASHBOARD_VIEWER,
    EKYC_CUSTOMER_PLATFORM_DASHBOARD_VIEWER,
    EXPIRE_CUSTOMER_REGISTRATION_TOKEN,
    FAN_CLUB_MANAGER,
    LOAN_REQUEST_SESSION_VIEWER,
    LOAN_REQUEST_SESSION_TELLER_OPS,
    LOAN_REQUEST_SESSION_TERMINATION_TELLER,
    LOAN_REQUEST_SESSION_ADD_LOAN_NUMBER,
    LOAN_REQUEST_SESSION_DASHBOARD_VIEWER,
    LOAN_REQUEST_SESSION_TELLER_STATISTIC_VIEWER,
    LONG_TERM_DEPOSIT_TEMPLATE_OPERATION,
    LONG_TERM_DEPOSIT_OPENING_TELLER,
    SHORT_TERM_DEPOSIT_TEMPLATE_OPERATION,
    SHORT_TERM_DEPOSIT_OPENING_TELLER,
    //forget password claims
    TELLER_FORGET_PASSWORD_SESSION_MANAGEMENT,
    FORGET_PASSWORD_SESSION_VIEWER,
    FORGET_PASSWORD_DASHBOARD_VIEWER,
    FORGET_PASSWORD_VIRTUAL_BRANCH_MANAGER,
    INTEREST_FREE_DEPOSIT_TEMPLATE_OPERATION,
    INTEREST_FREE_DEPOSIT_OPENING_TELLER,
    //attorney account claims
    ATTORNEY_ACCOUNT_BACKOFFICER,
    ATTORNEY_ACCOUNT_ADMIN,
    BUSINESS_USER_CHECK_CUSTOMER_FAN_CLUB,

    INVITATION_FESTIVAL_OPERATION,
    WAGE_SETTINGS_OPERATION,
    ISSUE_DEBIT_CARD_VIRTUAL_BRANCH_MANAGER,
    ISSUE_DEBIT_CARD_SESSION_VIEWER,


    // Profile & Account
    VIEW_PROFILE,
    UPDATE_PROFILE,
    CHANGE_PASSWORD,
    VIEW_ACTIVITY_LOG,

    // Transactions & Orders
    VIEW_TRANSACTIONS,
    VIEW_ORDERS,
    CREATE_ORDER,
    CANCEL_ORDER,
    VIEW_INVOICES,

    // Products & Services
    VIEW_PRODUCTS,
    SEARCH_PRODUCTS,
    VIEW_SERVICES,

    // Support Tickets (own tickets only)
    CREATE_TICKET,
    VIEW_MY_TICKETS,
    REPLY_MY_TICKET,
    CLOSE_MY_TICKET,

    // Notifications
    VIEW_NOTIFICATIONS,
    MARK_NOTIFICATION_READ,

    // Wallet & Balance
    VIEW_WALLET_BALANCE,
    CHARGE_WALLET,
    WITHDRAW_WALLET,

    // Security & Authentication
    ENABLE_2FA,
    DISABLE_2FA,
    VIEW_DEVICES,
    REMOVE_DEVICE,

    // Basic Access
    BASIC_ACCESS,
}
