spring.application.name=iam-service

server.port=@server.port@

spring.data.mongodb.uri=@spring.data.mongodb.uri@

spring.rabbitmq.host=@spring.rabbitmq.host@
spring.rabbitmq.port=@spring.rabbitmq.port@
spring.rabbitmq.username=@spring.rabbitmq.username@
spring.rabbitmq.password=@spring.rabbitmq.password@

orchestration.identityManagement.queue=orchestration.identityManagement.queue
rabbitmq.exchange=orchestration.exchange
identityManagement.routing.key=identityManagement.routing.key

mongock.change-logs-scan-package= io.github.mojtaba.microservice.starter.iam.dbchangelog

